### ISSUE TITLE
上映時刻をDatePicker(PC)や日付用のPulldownリスト(mobile)で操作したい

### ISSUE THREAD

**Issue by b4h0-c4t** [i544c/screening#10]
年月日全部別のpulldownになってるとちょっと使いにくかった(個人の感想)

**Comment by b4h0-c4t** [comment]
![486A928A-3014-448C-9645-B4188906AE10](https://user-images.githubusercontent.com/22951237/67376584-5da27f80-f5bf-11e9-9ee0-f96f6b8cb569.jpeg)
こういうやつです

**Comment by i544c** [comment]
@b4h0-c4t 解決済みなので閉じます！
